name: ncurses
variables:
  - build_type: release
  - ncurses_tag: v6.4
  - ncurses_url: https://github.com/mirror/ncurses.git
source:
  maintainer: Thomas_E_Dickey
  name: ncurses
  tag: ${ncurses_tag}
  repo_kind: git
  repo_url: ${ncurses_url}
  git_depth: 1
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${HPB_BUILD_DIR};
          [ "${build_type}" = "release" ] && ${HPB_SOURCE_PATH}/configure --prefix=${HPB_OUTPUT_DIR} --with-shared --with-normal --without-debug || echo "build type is not release";
          [ "${build_type}" = "debug" ] && ${HPB_SOURCE_PATH}/configure --prefix=${HPB_OUTPUT_DIR} --with-shared --without-normal --with-debug || echo "build type is not debug";
          make && make install;
          cd ${HPB_TASK_DIR};
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          hpb pack;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb push;
