find_path(NCURSES_INCLUDE_DIR
	NAMES ncurses/curses.h
	PATH_SUFFIXES include
	PATHS ${CMAKE_PREFIX_PATH})

string(TOLOWER ${CMAKE_BUILD_TYPE} LOWER_BUILD_TYPE)
if (${LOWER_BUILD_TYPE} STREQUAL "debug")
	message("try find ncurses libs with debug mode")

	find_library(LIB_NCURSES
		NAMES ncurses_g
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	find_library(LIB_NCURSES_PANEL
		NAMES panel_g
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	find_library(LIB_NCURSES_MENU
		NAMES menu_g
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	find_library(LIB_NCURSES_FORM
		NAMES form_g
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)
else()
	message("try find ncurses libs with release mode")

	find_library(LIB_NCURSES
		NAMES ncurses
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	find_library(LIB_NCURSES_PANEL
		NAMES panel
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	find_library(LIB_NCURSES_MENU
		NAMES menu
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	find_library(LIB_NCURSES_FORM
		NAMES form
		PATH_SUFFIXES lib
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)
endif()

# NOTE: for right link order, libncurses must link in the last 
set(NCURSES_LIBRARIES
	${LIB_NCURSES_PANEL}
	${LIB_NCURSES_MENU}
	${LIB_NCURSES_FORM}
	${LIB_NCURSES}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(NCURSES REQUIRED_VARS
	NCURSES_INCLUDE_DIR
	LIB_NCURSES_PANEL
	LIB_NCURSES_MENU
	LIB_NCURSES_FORM
	LIB_NCURSES
)
